// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1667297079);
user_pref("app.update.lastUpdateTime.region-update-timer", 1644615294);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1667296839);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1667296959);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1667297319);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1667297199);
user_pref("browser.region.update.updated", 1644614787);
user_pref("browser.search.region", "IN");
user_pref("browser.theme.dark-toolbar-theme", false);
user_pref("calendar.timezone.local", "Asia/Kolkata");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 1);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1644614795689");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 33);
user_pref("extensions.getAddons.cache.lastUpdate", 1667297079);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppBuildId", "20220106182030");
user_pref("extensions.lastAppVersion", "91.5.0");
user_pref("extensions.lastPlatformVersion", "91.5.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webextensions.uuids", "{\"default-theme@mozilla.org\":\"92da5d28-a2ca-4318-ae1c-9469822e55ce\",\"google@search.mozilla.org\":\"45a53298-c8c8-4b0f-b653-11dc1e593944\",\"ddg@search.mozilla.org\":\"b11bb7d8-417f-4c4f-aefa-19bbf5a88715\",\"amazondotcom@search.mozilla.org\":\"4bf456c6-706a-49ce-8c77-ca2fc6a6c697\",\"wikipedia@search.mozilla.org\":\"d0d0e434-c33c-44ca-b7d0-3868c0d8de75\",\"bing@search.mozilla.org\":\"47201f14-66a4-4a87-b4a7-12cccb82e2c0\"}");
user_pref("idle.lastDailyNotification", 1667297114);
user_pref("mail.ab_remote_content.migrated", 1);
user_pref("mail.ui-rdf.version", 30);
user_pref("mailnews.database.global.datastore.id", "d7336e01-c572-4ee2-a75c-d1fa0595c5d");
user_pref("mailnews.headers.extraAddonHeaders", "autocrypt openpgp");
user_pref("mailnews.quotingPrefs.version", 1);
user_pref("mailnews.start_page_override.mstone", "91.5.0");
user_pref("mailnews.tags.$label1.color", "#FF0000");
user_pref("mailnews.tags.$label1.tag", "Important");
user_pref("mailnews.tags.$label2.color", "#FF9900");
user_pref("mailnews.tags.$label2.tag", "Work");
user_pref("mailnews.tags.$label3.color", "#009900");
user_pref("mailnews.tags.$label3.tag", "Personal");
user_pref("mailnews.tags.$label4.color", "#3333FF");
user_pref("mailnews.tags.$label4.tag", "To Do");
user_pref("mailnews.tags.$label5.color", "#993399");
user_pref("mailnews.tags.$label5.tag", "Later");
user_pref("mailnews.tags.version", 2);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.trr.blocklist_cleanup_done", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("places.database.lastMaintenance", 1667297114);
user_pref("privacy.purge_trackers.date_in_cookie_database", "0");
user_pref("services.settings.clock_skew_seconds", -3428);
user_pref("services.settings.last_etag", "\"1648185887941\"");
user_pref("services.settings.last_update_seconds", 1667300386);
user_pref("services.settings.thunderbird.hijack-blocklists.last_check", 1667300386);
user_pref("services.settings.thunderbird.search-config.last_check", 1667300386);
user_pref("services.settings.thunderbird.url-classifier-skip-urls.last_check", 1667300386);
user_pref("storage.vacuum.last.index", 0);
user_pref("storage.vacuum.last.places.sqlite", 1667297114);
user_pref("toolkit.telemetry.cachedClientID", "89e874e6-6d1e-4834-8516-be28d002030d");
user_pref("toolkit.telemetry.previousBuildID", "20220106182030");
